# データ

- date.csv
 - courseマスタ (train - test共通)
- object.csv
 - moduleマスタ (train - test共通)
- eonrollment.csv
 - enroll履歴
- log.csv
 - 履歴
- submit
 - enrollment_id と ドロップアウトする確率

In [1]:
couses = pd.read_csv('./data/date.csv')

In [2]:
couses.head()

                          course_id        from          to
0  bWdj2GDclj5ofokWjzoa5jAwMkxCykd6  2014-05-26  2014-06-24
1  RXDvfPUBYFlVdlueBFbLW0mhhAyGEqpt  2014-05-25  2014-06-23
2  fbPkOYLVPtPgIt0MxizjfFJov3JbHyAi  2014-01-17  2014-02-15
3  A3fsA9Zfv1X2fVEQhTw51lKENdNrEqT3  2014-05-28  2014-06-26
4  5X6FeZozNMgE2VRi3MJYjkkFK8SETtu2  2014-06-09  2014-07-08

In [3]:
couses.describe()

                               course_id        from          to
count                                 39          39          39
unique                                39          26          26
top     nSfGxfEtzw5G72fVbfaowxsV46Pg1xIc  2014-05-26  2014-06-23
freq                                   1           4           4

In [4]:
modules = pd.read_csv('./data/object.csv')

In [5]:
modules.head()

,course_id,module_id,category,children,start
0,SpATywNh6bZuzm8s1ceuBUnMUAeoAHHw,L1s4VseGlRT302GZlJNStvtJZnvnr3IJ,about,NaN,null
1,SpATywNh6bZuzm8s1ceuBUnMUAeoAHHw,HxVne4dRqhXXf9FEsuUxVBG2THLkXgGV,about,NaN,null
2,SpATywNh6bZuzm8s1ceuBUnMUAeoAHHw,3fpwAdewUyNZkLToSwy7eWQmmglHzA0G,chapter,wq9HGmGdGoXFRgp4KQzo7WD8RSwwckZL X2rMpSy9lvzEe...,2014-08-11T01:00:00
3,SpATywNh6bZuzm8s1ceuBUnMUAeoAHHw,qEdbIFRbbfpjN4tkWOq8kMsxES84yPfy,chapter,nQZ5JRSJDlJ0XmlkYykP7iWt748Hp5uQ ehLxBxQUzqxrI...,2014-07-28T01:00:00
4,SpATywNh6bZuzm8s1ceuBUnMUAeoAHHw,q9vSHnqnL8T6MSYy1QZ1d1v8gb7HqKIc,chapter,aifkOeC4slG9VREeJqwyVeLriGIqAUjY 8u4PaPNvjqjSf...,2014-08-25T01:00:00

In [6]:
modules.describe()

,course_id,module_id,category,children,start
count,27249,27249,27249,13597,27249
unique,39,26750,15,13192,421
top,shM3Yy9vxHn2aqjSYfQXOcwGo0hWh3MI,LU9s55Z4Z0NlDWOaa6DraGvmO5FySHwU,vertical,EjQNwsK7dJS4ClWyreuXD9D7XwKs0uvB,null
freq,2113,2,9823,2,24925

In [14]:
modules.groupby(['course_id', 'category']).category.count().unstack().fillna(0)

category,about,chapter,combinedopenended,course,course_info,dictation,discussion,html,outlink,peergrading,problem,sequential,static_tab,vertical,video
course_id,,,,,,,,,,,,,,,
1pvLqtotBsKv7QSOsLicJDQMHx3lui6d,3,11,0,1,2,0,17,0,0,0,33,28,2,134,104
3VkHkmOtom3jM2wCu94xgzzu1d6Dn7or,4,9,0,1,2,0,21,91,3,0,44,52,1,123,55
3cnZpv6ReApmCaZyaQwi2izDZxVRdC01,3,7,0,1,2,0,0,1,1,0,231,125,1,261,110
5Gyp41oLVo7Gg7vF4vpmggWP5MU70QO6,3,13,0,1,2,0,5,28,1,0,59,73,1,200,112
5X6FeZozNMgE2VRi3MJYjkkFK8SETtu2,2,14,0,1,2,0,1,1,2,0,309,78,1,414,155
7GRhBDsirIGkRZBtSMEzNTyDr2JQm4xx,4,12,0,1,2,0,129,48,3,0,95,72,3,252,113
81UZtt1JJwBFYMj5u38WNKCSVA4IJSDv,3,15,0,1,2,0,0,0,2,0,11,90,1,78,66
9Bd26pfDLvkPINwLnpaGcf0LrLUvY1Mz,4,14,0,1,2,0,58,13,2,0,291,124,3,969,502
9Mq1P5hrrLw6Bh9X4W4ZjisQJDdxjz9x,3,12,0,1,2,0,0,2,4,0,17,61,3,150,132
9zpXzW9zCfU8KGBWkhlsGH8B8czISH4J,3,8,0,1,2,0,0,1,1,0,50,54,1,207,146
A3fsA9Zfv1X2fVEQhTw51lKENdNrEqT3,3,26,0,1,2,0,0,2,2,0,322,126,2,144,110
AXUJZGmZ0xaYSWazu8RQ1G5c76ECT1Kd,3,14,0,1,2,0,0,2,5,0,15,73,1,101,57
DABrJ6O4AotFwuAbfo1fuMj40VmMpPGX,4,18,3,1,2,0,0,5,2,2,43,102,0,122,91
DPnLzkJJqOOPRJfBxIHbQEERiYHu5ila,4,13,1,1,2,0,0,33,3,2,42,100,2,139,56
Er0RFawC4sHagDmmQZcBGBrzamLQcblZ,4,11,0,1,2,0,130,49,2,0,93,63,3,226,118
G8EPVSXsOYB5YQWZGiz1aVq5Pgr2GrQu,2,25,0,1,2,0,0,101,3,0,300,128,2,312,113
H2lDW05SyKnwntZ6Fora76aPAEswcMa5,2,12,0,1,2,11,1,2,3,0,54,80,3,107,65
HbeAZjZFFQUe90oTP0RRO0PEtRAqU3kK,3,15,0,1,2,0,0,12,2,0,468,110,3,436,260
I7Go4XwWgpjRJM8EZGEnBpkfSmBNOlsO,4,12,0,1,2,0,0,31,1,0,43,96,2,133,56
KHPw0gmg1Ad3V07TqRpyBzA8mRjj7mkt,2,12,0,1,2,0,1,0,0,0,31,74,1,114,79
NmbZ3BmS8V4pMg6oxXHWpqqMZCE1jvYt,3,14,0,1,2,0,6,29,1,0,64,85,1,231,136
RXDvfPUBYFlVdlueBFbLW0mhhAyGEqpt,4,17,0,1,2,0,4,31,3,0,193,119,1,198,86
SpATywNh6bZuzm8s1ceuBUnMUAeoAHHw,2,17,0,1,2,0,0,18,1,0,69,99,1,175,82
TAYxxh39I2LZnftBpL0LfF2NxzrCKpkx,4,12,0,1,2,0,16,0,1,0,31,29,2,132,103
V4tXq15GxHo2gaMpaJLZ3IGEkP949IbE,4,20,8,1,2,0,37,165,3,8,98,77,3,260,114
WM572q68zD5VW8pcvVTc1RhhFUq3iRFN,3,13,0,1,2,0,113,116,3,0,109,116,2,459,113
Wm3dddHSynJ76EJV6hyLYKGGRL0JF3YK,3,15,0,1,2,0,0,2,1,0,465,109,3,482,273
X78EhlW2JxwO1I6S3U4yZVwkEQpKXLOj,4,16,0,1,2,0,0,0,0,0,16,111,2,119,100
a2E7NQC7nZB7WHEhKGhKnKvUWtsLAQzh,4,19,3,1,2,0,0,2,5,0,85,189,0,272,205
bWdj2GDclj5ofokWjzoa5jAwMkxCykd6,2,14,0,1,2,0,0,2,2,0,137,45,1,95,37
fbPkOYLVPtPgIt0MxizjfFJov3JbHyAi,3,8,0,1,2,0,1,10,5,0,33,43,1,78,36
gvEwgd64UX4t3K7ftZwXiMkFuxFUAqQE,2,16,0,1,2,0,0,1,3,0,61,91,3,178,152
mTmmr5zd8l4wXhwiULwjSmSbi9ktcFmV,4,7,0,1,2,0,52,7,1,0,50,66,1,313,235
nSfGxfEtzw5G72fVbfaowxsV46Pg1xIc,3,15,0,1,2,0,260,1,2,0,306,60,2,349,150
q6A6QG7qMpyNcznyT2XaIxnfNGkZRxXl,4,10,0,1,2,0,298,1,2,0,173,62,1,308,137
shM3Yy9vxHn2aqjSYfQXOcwGo0hWh3MI,4,19,0,1,2,0,473,2,4,0,500,130,3,719,256
tXbz2ZYaRyb2ZsWUBPoYzAmisOhHQrYl,3,14,0,1,2,0,115,133,2,0,117,118,1,476,122
xMd9DzNyUCTLRPVbwWVzf4vq06oqrTT1,3,12,0,1,2,0,0,23,0,0,61,160,1,175,85
ykoe1cCWK134BJmfbNoPEenJOIWdtQOZ,3,16,3,1,2,0,0,1,4,3,16,133,2,182,129

In [15]:
modules[['module_id', 'category']]

                              module_id     category
0      L1s4VseGlRT302GZlJNStvtJZnvnr3IJ        about
1      HxVne4dRqhXXf9FEsuUxVBG2THLkXgGV        about
2      3fpwAdewUyNZkLToSwy7eWQmmglHzA0G      chapter
3      qEdbIFRbbfpjN4tkWOq8kMsxES84yPfy      chapter
4      q9vSHnqnL8T6MSYy1QZ1d1v8gb7HqKIc      chapter
5      jChJZWA7TPrU7h1y5uZfnwajue9MzGBn      chapter
6      54D4zY2cdRyG83ZfykBka35LzNS04AXi      chapter
7      zDoPYVWL0APn1CAim3uMOBoSA6sGt9MZ      chapter
8      lFaL098pNcCMxay4b7YvzwmolqCVT03N      chapter
9      I6LKQXheMldlnI1vCTZBBVq3RxLAOxpE      chapter
10     0lrB7xh60Mnfp83JZY0GbnYiVgQIcdBz      chapter
11     W569V82FPFMc3YKyMh7mUoAaiYAESfci      chapter
12     t62YLbx6JfoGf6znvwn2yvoAkQP47N3O      chapter
13     sZheQFLQDOSqmjBA12i2NVVuHTmiLaDm      chapter
14     9bc4yoavNlSifbTbZjUCdAQenbV5LByB      chapter
15     1KcQ0YSPih8dCJxia9uRrGylbGPaEsTO      chapter
16     EwNhr3X73GNTY20P0JN6AlQndvSuRwhN      chapter
17     PdIDJgFPNrcCtmegviCbPbzeyoQF0K58      chapter
18     imDqISq6D3vp4nqjskdKt4XxLvD9AOUd      chapter
19     LHbqwkRX6hEG5rc7z2hNSfpcUSDHLo4m       course
20     g0Q3zVjvoz0dyzIsXyQfhX0ebFH0AJ5Y  course_info
21     4ce8fAjrMeCFTlKZuofQEOaULIdbRAe8  course_info
22     h1ch77pnXr6XYHCPYxJr5INwsVTtMXlo         html
23     mvpQStOh3NAWL5lbi2QPNGjmUyhjUQNO         html
24     0YtnClw7eYjb0udEXkrjAQxRY1v9lxJ2         html
25     hqINOwgj0k0SdGyQcAejywUCcczZLa6O         html
26     tuDZdrXYmfYyUTk9o4VV3bU6I88AqiiJ         html
27     w7rr3etQTv55jXxNPaOrMOMnPd7Lnib7         html
28     vWL7Cm1K6qVs98rSJ1RtUn3sEJvt0nrh         html
29     rwu7P61ZY6diHNxWKs3zgKaqC5lRUHk7         html
...                                 ...          ...
27219  JLXi34lIi1wadcFl1G8ocb8uy0uEImkv        video
27220  gw76JTmPB5OetA6qr3CiuPFNz5GIeUiO        video
27221  jc3a0pqHmdJQi0NRZqJujTYkdWRzqBmT        video
27222  7KKNkGgn9bEHrrmnurjmQtcORezkrZlk        video
27223  00356MwdHIKtYac8z7ECu16KbvCu7OFx        video
27224  jxTRsHYdTMVavuNZe36eBgh7tG84FIGY        video
27225  ggI75PrZac4ZgwY5zVcFxj2Sd22XeBMv        video
27226  HXwWYwfPglHjEAjLzPeGrWR7KZgpZCgi        video
27227  A0fZEfNpHj7iC9Q8PJ9vMT8TKNPnvSpr        video
27228  mt0MayAetnY7Q992XMCVeqnw88VCLY9N        video
27229  RWIcRoyTdkfdPU5mKxSBkJ4EZeRoAuA4        video
27230  HAPDtdXtI2i4MzVMaopJFxhPWXuHrWql        video
27231  vgiyNnEeOpzdVxDeuSGEmcihC9HaF0yZ        video
27232  KkZWJZMsUe2p127FJCKSjnR5XXT2ZW5s        video
27233  Ru3uYNDCJTZ9TSOH8gXyI2Iprcp1Niko        video
27234  B5d404cq3fvYiuV0CZGRdIj5YiDNRLAq        video
27235  2t68muFfWT9t9795QW7lUhGwJiE54sAz        video
27236  VMw3sRG2MUv6ZD3GUwCQTWjtb61pMTqm        video
27237  uB48Tcq0kKBYLSVtDyDQaObmGsjt0EPe        video
27238  En0wgTaHwmX8pU9uthWdG3Iv7SRyHIKj        video
27239  R7MaYJUAQx91xRTWI3bbfFxzy1ilNoOT        video
27240  0L3iraEVEt0t2snqm9OswWTNNJKBKcB4        video
27241  GznQhjywj8OG4MV3i6RvGshkV6pSPzBX        video
27242  UQrJ4cYp6TBHXmHPIER4xtMmcLHOvEV8        video
27243  QfvY7s9HFrUNFIn7A5lwQo5mfY82kOHZ        video
27244  tcxZZkSgyfSFRfidqqLjWqxudd39EWq8        video
27245  5o4BVVGEv1PURG8qIPf9pdfUjM7fj784        video
27246  46mqwKmgqhDUcUwCOl4iTWZQd1rGnfcd        video
27247  LY90uupLMTDQkhk0tgVhnayIQkvLqvbV        video
27248  juKcxcdjVMHkQ5BjYeEJj9dQGhedFYy2        video

[27249 rows x 2 columns]

In [8]:
train_enroll_df = pd.read_csv('./data/train/enrollment_train.csv')

In [9]:
train_enroll_df.groupby('username').course_id.count().describe()

count    79186.000000
mean         1.522264
std          1.192827
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         27.000000
dtype: float64

In [34]:
train_enroll_df.index.size

120542

In [35]:
train_enroll_df.course_id.unique().size

39

In [36]:
train_enroll_df.username.unique().size

79186

In [37]:
train_enroll_df.head()

,enrollment_id,username,course_id
0,1,9Uee7oEuuMmgPx2IzPfFkWgkHZyPbWr0,DPnLzkJJqOOPRJfBxIHbQEERiYHu5ila
1,3,1qXC7Fjbwp66GPQc6pHLfEuO8WKozxG4,7GRhBDsirIGkRZBtSMEzNTyDr2JQm4xx
2,4,FIHlppZyoq8muPbdVxS44gfvceX9zvU7,DPnLzkJJqOOPRJfBxIHbQEERiYHu5ila
3,5,p1Mp7WkVfzUijX0peVQKSHbgd5pXyl4c,7GRhBDsirIGkRZBtSMEzNTyDr2JQm4xx
4,6,dpK33RH9yepUAnyoywRwBt1AJzxGlaja,AXUJZGmZ0xaYSWazu8RQ1G5c76ECT1Kd

In [38]:
train_log_df = pd.read_csv('./data/train/log_train.csv')

In [39]:
train_log_df.head()

,enrollment_id,time,source,event,object
0,1,2014-06-14T09:38:29,server,navigate,Oj6eQgzrdqBMlaCtaq1IkY6zruSrb71b
1,1,2014-06-14T09:38:39,server,access,3T6XwoiMKgol57cm29Rjy8FXVFcIomxl
2,1,2014-06-14T09:38:39,server,access,qxvBNYTfiRkNcCvM0hcGwG6hvHdQwnd4
3,1,2014-06-14T09:38:48,server,access,2cmZrZW2h6Il91itO3e89FGcABLWhf3W
4,1,2014-06-14T09:41:49,browser,problem,RMtgC2bTAqEeftenUUyia504wsyzeZWf

In [40]:
train_log_df.groupby('source').source.count()

source
browser    3869940
server     4287337
Name: source, dtype: int64

In [41]:
train_log_df.groupby('event').source.count()

event
access        3112191
discussion     649259
navigate      1009309
page_close    1237883
problem       1261170
video          796958
wiki            90507
Name: source, dtype: int64

In [50]:
df = train_log_df.groupby(['enrollment_id', 'event']).event.count()

In [10]:
pd.DataFrame(df).unstack().event.fillna(0).head()

NameError: name 'df' is not defined